### ISSUE TITLE
Dependencies look a bit old

### ISSUE THREAD

**Issue by dottorblaster** [apdunston/random_words#2]
During `mix deps.get` I've got a minor warning :-)

```
warning: the dependency :ex_doc requires Elixir "~> 1.3.0 or ~> 1.4.0 or ~> 1.5.0 or ~> 1.6.0" but you are running on v1.10.3
```

**Comment by apdunston** [comment]
@dottorblaster , thank you so much for using random words and for sending issue reports. I have looked into this issue, found the problem, and I believe I have fixed it. Please try random_words 1.0.1, and confirm that this issue is solved. Thank you again!

**Comment by dottorblaster** [comment]
@apdunston fixed! Thank you so much!
